### ISSUE TITLE
MongoDB on RADICAL vm is not usable for experiments on XSEDE and BlueWaters

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#1071]
Less than 1/3 of CUs reach state 'Done'. This is observed consistently and as a result not even a single simulation cycle can finish. Switching to mlab's MongoDB seems to solve the issue, but mlab is not suitable for experiments: http://docs.mlab.com/production-guide/#predictable-performance

**Comment by marksantcroos** [comment]
This is probably the same as #1068, but with a useful pointer that it might be latency related.

**Comment by antonst** [comment]
I don't think this is entirely caused by the location of the MongoDB. I have used a MongoDB instance running on RADICAL-VM, EC2, jetstream, mlab and my laptop and I encountered this issue in those case as well. Additionally, location of the client does not improve things a lot, I have used  RADICAL-VM, jetstream and my laptop to launch experiments. I would like to understand one thing. Which of the following is causing this:
 - changes in new version of MongoDB (3.2.6)?
 - changes in new version of RP(0.41)?
 - changes at the system level (Stampede)?
 - something else?

It seems that issue is not related to the concurrency of the CUs, simulation stalls after approximately 3000 CUs, regardless of how many of them run concurrently. To get any run through I have to submit it more than 5 times, which basically makes RP unusable for the experiments I am doing.

**Comment by marksantcroos** [comment]
Thanks for the further diagnose.

> changes in new version of RP(0.41)?

Im not sure it is new, but it is an RP issue.

**Comment by iparask** [comment]
@andre-merzky , do you remember that we faced a similar problem and you said that it may have been the OutputFileTransferWorker? I remember we had a branch for that? I cannot find it.

**Comment by marksantcroos** [comment]
Its the update worker on the agent.

**Comment by andre-merzky** [comment]
indeed - it is not that things are not happening, units progress ok, the problem is that the agent update worker fails to communicate that to the DB... :/

**Comment by andre-merzky** [comment]
I pushed a fix to `fix/state_update_sorting` -- Antons, could you please give it a try?

**Comment by antonst** [comment]
I gave it a try. All of my units are failing now with:
```
/opt/apps/intel13/mvapich2_1_9/amber/12.0/bin/sander: error while loading shared libraries: libsvml.so: cannot open shared object file: No such file or directory
```

**Comment by antonst** [comment]
I am running with an artificial workload now. Will let you know the outcome soon.

**Comment by antonst** [comment]
In RP: v0.42-143-gcefbb3b@devel this issue is still present. For one of my 1000 concurrent CUs runs on Stampede 206 CUs never reached 'Done' state. All of them were hanging in 'PendingOutputStaging'. I have manually checked for a couple of CUs and output files actually were transferred, but no state update occurred.

**Comment by marksantcroos** [comment]
Hmmm, not good.

When you say "CUs never reached 'Done' state", where do you base that on? The database, what the client sees, something else?

Thanks!

**Comment by andre-merzky** [comment]
Can you please send the logfiles and the DB dump?  Thanks.

**Comment by antonst** [comment]
I could not fetch the session from db:

```
modes   : export
db url  : mongodb://rp:rp@ds015335.mlab.com:15335/rp
session : rp.session.js-169-156.jetstream-cloud.org.antontre.017035.0001
age     : -999999999 days, 0:00:00
Traceback (most recent call last):
  File "/home/antontre/util-async/bin/radicalpilot-close-session", line 271, in <module>
    elif m == 'export': export_sessions (db, dbname, age, session) 
  File "/home/antontre/util-async/bin/radicalpilot-close-session", line 176, in export_sessions
    sessions = get_sessions (db, dbname, age, session)
  File "/home/antontre/util-async/bin/radicalpilot-close-session", line 77, in get_sessions
    docs = rpu.get_session_docs (db, sid)
  File "/home/antontre/util-async/local/lib/python2.7/site-packages/radical/pilot/utils/db_utils.py", line 98, in get_session_docs
    raise ValueError ('no session %s in db (was `cleanup` disabled on `session.close()`?)' % sid)
ValueError: no session rp.session.js-169-156.jetstream-cloud.org.antontre.017035.0001 in db (was `cleanup` disabled on `session.close()`?)
```

Log is here:
[log])https://github.com/antonst/rp-logs/blob/master/stamp-qmmm-async-r1000-c1008-a888-s2000-w05.log)

>When you say "CUs never reached 'Done' state", where do you base that on?

What I see in the log.

**Comment by andre-merzky** [comment]
The log says you had a connection error at 15:52, and a failing unit (unit.010993) right after that, presumable because the connection failure screwed with output staging, which was active at that point (it killed an ssh channel).  At 16:23 you had another set of connection errors, and again a unit failed for the same reasons then.   With those ssh channels gone, both output workers were dead and thus stopped staging, that is why you see all the units hanging around in 'pending output staging' state.

 At 18:43 a pilot job was found to have died, and the subsequent termination got screwed up by Python's signal handling (not sure if termination succeeded or the application got hung up.

I can't say much on the reasons for the connection errors: they look like a DNS timeouts, so I assume that the network dropped (on either end):

```
ssh: Could not resolve hostname stampede.tacc.utexas.edu: No address associated with hostname
```

HtH, Andre.

**Comment by antonst** [comment]
>The log says you had a connection error at 15:52, and a failing unit (unit.010993) right after that, presumable because the connection failure screwed with output staging, which was active at that point (it killed an ssh channel)

Thanks for pointing this out Andre. Out of ~12600 units I had 2 failures, both of these were exchange tasks and should not affect execution of other units.

>At 16:23 you had another set of connection errors, and again a unit failed for the same reasons then. With those ssh channels gone, both output workers were dead and thus stopped staging, that is why you see all the units hanging around in 'pending output staging' state.

OK, so this explains it. Not sure how this helps me though.   

>At 18:43 a pilot job was found to have died, and the subsequent termination got screwed up by Python's signal handling (not sure if termination succeeded or the application got hung up.

From 16:29 to 18:43 pilot was just hanging there, since application stopped unit submission due to hanging units.

I guess I should close this ticket again then? Which ticket I should reference instead?

**Comment by andre-merzky** [comment]
#435  is related, which is concerned about fail tolerance on file transfers in general, but I don't mind if you keep this ticket open to specifically remind us to look into resilience for ssh connection drops. I doubt this will get implemented/fixed/improved quickly though :/

**Comment by antonst** [comment]
OK, I will keep this ticket open then. No worries Andre, while failures are affecting productivity, I still can run my experiments. This is not something that is stopping me and I am not expecting this issue to be resolved immediately.

**Comment by andre-merzky** [comment]
#1090  should address the pending units, #1129 is now open to capture all reconnect issues -- thus closing this ticket.  Thanks!
