### ISSUE TITLE
CU using home directory in 'state_dir' fails on Titan

### ISSUE THREAD

**Issue by jrossyra** [radical-cybertools/radical.pilot#1538]
I am using a similar setup as with the issues I previously posted, except now using the `issue/1418` branch. The current hangup in execution seems related to Titan's home directory not being mounted to the compute nodes (though the PBS_O_HOME is this directory). Specifically, I'm getting this error where a `makedirs` is attempted on `$HOME` subdirectory: 

`cat agent_1.err`
```2018-01-23 15:08:54,415: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.9 (default, May 6 2016, 10:34:30) [GCC 4.9.0 20140422 (Cray Inc.)]
2018-01-23 15:08:54,416: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 25349
2018-01-23 15:08:54,416: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2018-01-23 15:08:54,417: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: 0.47-v0.46-33-g3c75f23@devel
2018-01-23 15:08:54,707: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.9 (default, May 6 2016, 10:34:30) [GCC 4.9.0 20140422 (Cray Inc.)]
2018-01-23 15:08:54,707: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 25349
2018-01-23 15:08:54,707: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
Traceback (most recent call last):
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/bin/radical-pilot-agent", line 26, in <module>
    rp.agent.bootstrap_3(agent_name)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/bootstrap_3.py", line 44, in bootstrap_3
    agent = Agent_n(agent_name)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_n.py", line 60, in __init__
    session = rp_Session(cfg=session_cfg, _connect=False)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 148, in __init__
    rs.Session.__init__(self)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/lib/python2.7/site-packages/saga/session.py", line 176, in __init__
    simple_base.__init__ ()
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/lib/python2.7/site-packages/saga/base.py", line 37, in __init__
    self._id     = ru.generate_id (self._get_apitype (), mode=ru.ID_SIMPLE)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/ids.py", line 181, in generate_id
    return _generate_id(template, prefix, namespace)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/ids.py", line 198, in _generate_id
    os.makedirs(state_dir)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: '/ccs/home/jrossyra'
```

@itomaldonado  suspects that this error might arise from the `saga` layer, where the problem on line 198 in the file `ids.py` is really due to how `state_dir` is constructed: 

`_BASE        = "%s/.radical/utils" % os.environ.get("HOME", "/tmp")`

I do have the pilot and unit input staging happen successfully, and but the CU execution does not occur. I have just killed the session from the keyboard while it's hanging. Here are the logs, thanks!

[rp.client.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1658205/rp.client.tar.gz)
[rp.agent.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1658207/rp.agent.tar.gz)

**Comment by andre-merzky** [comment]
Uh, that's a funny one...  Indeed, `$HOME` is not available on the Titan compute nodes, and the ID generation screws up.  But I am still surprised since the session ID should have been generated on the client side, and should not get freshly generated in the agent.  Also, this did not pop up on Titan before...

Thanks for the tarballs and stacktrace,  I'll dig through it.

**Comment by andre-merzky** [comment]
Yeah, it seems like we introduced that recently with a feature merge.  The problem actually existed before, but a strategically places try/catch managed to mask it - it got exposure due to the merge.

How urgent is the fix - it sounds like are you stuck because of this, since you need that branch right now?

**Comment by jrossyra** [comment]
I do need to overcome this to have my workflow execute :/

**Comment by andre-merzky** [comment]
understood

**Comment by andre-merzky** [comment]
John, can you please try branch `fix/issue_1538` for both radical.pilot and saga-python?  Unfortunately, the fix involves both layers....

**Comment by jrossyra** [comment]
I ran a test and it looks like the orte library isn't found, this output was from `agent_0.err` with a similar error in `agent_0.log`. No `Tracebacks` in the client logs. 

```
orte-info: error while loading shared libraries: libopen-rte.so.0: cannot open shared object file: No such file or directory
orte-info: error while loading shared libraries: libopen-rte.so.0: cannot open shared object file: No such file or directory
orte-info: error while loading shared libraries: libopen-rte.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017555.0000/pilot.0000/rp_install/bin/radical-pilot-agent", line 26, in <module>
    rp.agent.bootstrap_3(agent_name)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017555.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/bootstrap_3.py", line 42, in bootstrap_3
    agent = Agent_0(agent_name)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017555.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 120, in __init__
    session=self._session)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017555.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 220, in create
    return impl(cfg, session)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017555.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/torque.py", line 19, in __init__
    LRMS.__init__(self, cfg, session)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017555.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 150, in __init__
    rp.agent.LM.lrms_config_hook(lm, self._cfg, self, self._log))
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017555.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 166, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger)
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017555.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 54, in lrms_config_hook
    oi_output = subprocess.check_output(['orte-info|grep "Open RTE"'], shell=True)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['orte-info|grep "Open RTE"']' returned non-zero exit status 1
```

**Comment by andre-merzky** [comment]
Ah, thanks for your patience.  I updated the branch now which points to a different ORTE version.  Too much environment churn on Titan ... :/

**Comment by jrossyra** [comment]
No problem, thanks for keeping at it! At this time it's back to trying to make the home directory per `agent_1.err`. I saved the logs, and checked the radical-stack to verify the install:

[rp.agent.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1662472/rp.agent.tar.gz)
[rp.client.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1662473/rp.client.tar.gz)

```
(admdrpenv) [jrossyra@titan-ext7 /lustre/atlas/proj-shared/bip149/jrossyra/admdrp2/admdrp/runs/runs/testpath01]$ radical-stack
2018-01-24 22:17:40,261: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.9 (default, May 6 2016, 10:34:30) [GCC 4.9.0 20140422 (Cray Inc.)]
2018-01-24 22:17:40,261: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 21476
2018-01-24 22:17:40,261: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2018-01-24 22:17:40,261: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: 0.47-v0.46-36-g5a6c32f@fix-issue_1538
2018-01-24 22:17:40,293: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.9 (default, May 6 2016, 10:34:30) [GCC 4.9.0 20140422 (Cray Inc.)]
2018-01-24 22:17:40,293: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 21476
2018-01-24 22:17:40,293: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread

  python               : 2.7.9
  pythonpath           : /sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /lustre/atlas/proj-shared/bip149/jrossyra/admdrp2/admdrpenv

  radical.pilot        : 0.47-0.47-6-g888f2aa@fix-issue_1538
  radical.utils        : 0.47-v0.47-4-gcca43d5@devel
  saga                 : 0.47-v0.46-36-g5a6c32f@fix-issue_1538
``

**Comment by andre-merzky** [comment]
Hi John, 

it seems you are not on the right branch, at least for saga-python, but likely also for RP.  Your stack shows:

```
  File "/lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext7.jrossyra.017554.0003/pilot.0000/rp_install/lib/python2.7/site-packages/saga/session.py", line 176, in __init__
    simple_base.__init__ ()
```

but the saga-python code should now have in that line:

```
 [fix/issue_1538] $ head -n 176 src/saga/session.py | tail -n 1
        simple_base.__init__ (uid=uid)
```

That uid passing is what is supposed to avoid the `mkdir` codepath.  Would you mind checking your output of `radical-stack`?  it should show something like:

```
 $ rs
  ...
  radical.pilot        : 0.47-0.47-4-g0c3fe75a@fix-issue_1538
  radical.utils        : 0.47
  saga                 : 0.47-v0.46-36-g5a6c32f5@fix-issue_1538
```

**Comment by jrossyra** [comment]
I tried a fresh reinstall of the environment and stack, but I am still having the makedirs error in `agent_1.err`. I do have this line with `uid` being passed in the site-package file. 

```(admdrpenv) [jrossyra@titan-ext7 /lustre/atlas/proj-shared/bip149/jrossyra/admdrp3/admdrp/runs/runs/testpath03]$ head -n176 /lustre/atlas/scratch/jrossyra/bip149/radical.pilot.sandbox/rp.session.titan-ext2.jrossyra.017557.0002/pilot.0000/rp_install/lib/python2.7/site-packages/saga/session.py  | tail -n1
        simple_base.__init__ (uid=uid)
```

The `radical-stack` shows utils on the devel branch, but otherwise the same versions. 
```(admdrpenv) [jrossyra@titan-ext7 /lustre/atlas/proj-shared/bip149/jrossyra/admdrp3/admdrp/runs/runs/testpath03]$ radical-stack

  python               : 2.7.9
  pythonpath           : /sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /lustre/atlas/proj-shared/bip149/jrossyra/admdrp3/admdrpenv

  radical.pilot        : 0.47-0.47-6-g888f2aa@fix-issue_1538
  radical.utils        : 0.47-v0.47-4-gcca43d5@devel
  saga                 : 0.47-v0.46-36-g5a6c32f@fix-issue_1538
```

Here are the logs from this last round.
[rp.agent.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1669673/rp.agent.tar.gz)
[rp.client.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1669674/rp.client.tar.gz)

**Comment by mturilli** [comment]
Ping. This issue is blocking for AdaptiveMD project.

**Comment by jrossyra** [comment]
Thanks Matteo. Let me know if there's anything else I can do print out information from execution, I'd be happy to run it again. Like I mentioned, to me it does look like this code was changed when I reinstalled my stack.

**Comment by mturilli** [comment]
@andre-merzky it seems that the fix did not fix John's problem. How should we proceed?

**Comment by jrossyra** [comment]
Andre,
Here's output logs & stack printout from the test with the AdaptiveMD branch. It still looks to be the same error, where the `state_dir`  wants to be made in the home directory. 

```
  python               : 2.7.9
  pythonpath           : /sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /lustre/atlas/proj-shared/bip149/jrossyra/admdrp4/admdrpenv

  radical.pilot        : 0.47-0.47-15-gc447dcb@project-adaptivemd
  radical.utils        : 0.47-v0.47-4-gcca43d5@project-adaptivemd
  saga                 : 0.47-v0.46-37-g01fbb26@project-adaptivemd
```

Let me know if there's anything else I can do to help investigate. Thanks again!

[rp.agent.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1711871/rp.agent.tar.gz)

**Comment by andre-merzky** [comment]
John, 

I pushed an update to the `project/adaptivemd` branch of SAGA - can you please update it on the client side (make sure to run `pip install`), and try again?  Thanks!

**Comment by jrossyra** [comment]
It looks like similar / same error in the agent_1 file. I am going to reinstall the whole stack to test it again, then can post the logs from there. It shouldn't take long.

**Comment by jrossyra** [comment]
Confirmed its a real bugger after reinstall. Here's my stack showing the updated saga repo, and the agent logs.

```
  python               : 2.7.9
  pythonpath           : /sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /lustre/atlas/proj-shared/bip149/jrossyra/admdrp/admdrpenv

  radical.pilot        : 0.47-0.47-15-gc447dcb@project-adaptivemd
  radical.utils        : 0.47-v0.47-4-gcca43d5@project-adaptivemd
  saga                 : 0.47-v0.46-38-g8b60236@project-adaptivemd
```
[rp.agent.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1712134/rp.agent.tar.gz)

**Comment by andre-merzky** [comment]
Thanks John - that gets us one step further.  GIve me some min please to iterate once more...

**Comment by andre-merzky** [comment]
Hi John, I pushed two more fixes which tackle the problem more fundamentally now, to the RP and RU layer.  If you don't mind, please give it another try.  I'll meanwhile try to find out why your are stumbling over that and I don't - that was not expected to happen at this point...

**Comment by jrossyra** [comment]
Ok sounds good, I'll run the tests again and report back soon. Thanks for looking at it!

**Comment by jrossyra** [comment]
Looks like this one is solved, I have some other errors that happen inside the CU so I think it's safe to close this. I'll look further into the current issues, which may be for Manuel and I to sort out. Thanks very much Andre! and let me know if there's any further info you'd like me to post for this issue.

**Comment by andre-merzky** [comment]
Puh, finally!  Thanks for your patience, John!

**Comment by itomaldonado** [comment]
Reopened this issue, PR #1539 did not address this issue. The commit that adds the variable `RADICAL_BASE_DIR` did not make it into the PR. Also, the variable was set for the ORTE launch method but *not* for the APRUN method. It is needed for both.

**Comment by itomaldonado** [comment]
Reopened this issue, PR #1539 did not address this issue. The commit that adds the variable `RADICAL_BASE_DIR` did not make it into the PR. Also, the variable was set for the ORTE launch method but _not_ for the APRUN method. It is needed for both.

**Comment by andre-merzky** [comment]
Hmm, that var is not needed - I only added it for additional flexibility.  The real fix is to test `$HOME` with `os.path.isdir`, which fails on Titan's compute node (the FS is not shared), and the next fallback is the `$PWD` - that is available and should avoid the error.

Can you attach a set of logfiles (or a pointer to the titan sandbox) for the fresh run please?  Obviously I am missing something...  Thanks!

**Comment by itomaldonado** [comment]
I take your word for it señor @andre-merzky! 

If you say this var is not needed, then we are fine. We will wait for @vivek-bala to test once the utils PR is merged (I saw @andre-merzky already did).

The only reason I re-oppened this was because in the other branch (`project/adaptivemd`) we have *all three* fixes, the utils, the rp and the variable in the resource config so I wanted to make sure this was not something we were missing.

**Comment by andre-merzky** [comment]
Hmmm... - let me double check :-)

**Comment by andre-merzky** [comment]
Yeah, this looks good.  I'll run a test on titan.

**Comment by andre-merzky** [comment]
UID issue is resolved - the remaining titan issues stay open though.
