### ISSUE TITLE
orte-dvm missing on Blue Waters

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1667]
Running an RP example using `ORTE` on `Blue Waters` with the release stack:

```
radical.pilot        : 0.50.3-v0.50.3@master
radical.utils        : 0.50.1-v0.50.1-1-gce60836@master
saga                 : 0.50.0-v0.50.0@master
```

[orte_deployment_gone.zip](https://github.com/radical-cybertools/radical.pilot/files/2192600/orte_deployment_gone.zip)
The client files are attached, issues at the `pmgr`. The agent response:

```
Traceback (most recent call last):
  File "/scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017725.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 154, in __init__
    self._log, self._prof))
  File "/scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017725.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 174, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger, profiler)
  File "/scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017725.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 48, in lrms_config_hook
    raise Exception("Couldn't find orte-dvm")
Exception: Couldn't find orte-dvm
```

Confirmed with @andre-merzky on the state of `ORTE` on Blue Waters, which appears to have disappeared and will require a new deployment.

**Comment by andre-merzky** [comment]
ompi has been redeployed, this should be fixed now.  Please do confirm if so.

**Comment by jdakka** [comment]
I still have the same issue: 

```
2018-07-13 16:42:32,849: agent_0             : MainProcess                     : MainThread     : INFO    : call LRMS config hook for LaunchMethod ORTE: <class 'radical.pilot.agent.lm.orte.ORTE'>
2018-07-13 16:42:32,890: agent_0             : MainProcess                     : MainThread     : ERROR   : lrms config hook failed
Traceback (most recent call last):
  File "/scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017725.0004/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 154, in __init__
    self._log, self._prof))
  File "/scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017725.0004/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 174, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger, profiler)
  File "/scratch/sciteam/dakka/radical.pilot.sandbox/rp.session.two.jdakka.017725.0004/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 48, in lrms_config_hook
    raise Exception("Couldn't find orte-dvm")
Exception: Couldn't find orte-dvm
```

**Comment by SrinivasMushnoori** [comment]
I have just tested my workload on BW with orte. 
I also face this issue.

**Comment by andre-merzky** [comment]
The ORTE installation on BW seems to be viable.  I released and merged the bwpy fixes now (`v0.50.7`), and also merged this into the DA scheduler branch.  The following stack seems to work ok on bw, with the `ncsa.bw_orte` resource label:

```
  python               : 2.7.14
  pythonpath           : /opt/xalt/0.7.6/sles11.3/libexec
  virtualenv           : /u/sciteam/merzky/rp_bw/ve

  radical.pilot        : 0.50.7-v0.50.7-98-gba799149@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@master
  saga                 : 0.50.0-v0.50.0@master
```

Please remember that you will still need to manually create a new pilot VE in the sandbox root, with something like:

```
radical-pilot-create-static-ve ve.ncsa.bw_orte.0.50.7 bw
```

**Comment by andre-merzky** [comment]
I have to take the last comment back - there is still an issue with the slot interpretation in the ORTE lm.  Will fix.

**Comment by andre-merzky** [comment]
This one should be correct (one additional commit on RP): 

```
  radical.pilot        : 0.50.7-v0.50.7-99-g4193371a@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@master
  saga                 : 0.50.0-v0.50.0@master
```

**Comment by SrinivasMushnoori** [comment]
I still face an issue.

Unit sandbox are not being created, and inside `pmgr.0000.launching.0.child.log` we have the following messages:

```
pmgr.0000.launching.0.child.log:2018-08-01 10:33:43,383: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : finalization error
pmgr.0000.launching.0.child.log:NoSuccess: read from process failed '[Errno 5] Input/output error' : (3616c2e7574696c732d302e35302e312d76302e35302e312d312d6763653630383336
2d646576656c2e7461722e677a0a736167612d707974686f6e2d302e35302e302d76302e35302e302d646576656c2e7461722e677a0a
pmgr.0000.launching.0.child.log:RuntimeError: finalize: read from process failed '[Errno 5] Input/output error' : (3616c2e7574696c732d302e35302e312d76302e35302e312d312d676
36536303833362d646576656c2e7461722e677a0a736167612d707974686f6e2d302e35302e302d76302e35302e302d646576656c2e7461722e677a0a
pmgr.0000.launching.0.child.log:2018-08-01 10:33:43,384: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : finalization error
pmgr.0000.launching.0.child.log:NoSuccess: read from process failed '[Errno 5] Input/output error' : (3616c2e7574696c732d302e35302e312d76302e35302e312d312d6763653630383336
2d646576656c2e7461722e677a0a736167612d707974686f6e2d302e35302e302d76302e35302e302d646576656c2e7461722e677a0a
```

This message is followed by much larger error messages that I cannot copy/paste here. I've included complete logs [here](https://github.com/radical-cybertools/radical.pilot/files/2249880/message_larger_than_1024.tar.gz)

`radical-stack` is:
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.4-0.7.3-10-gaffd55e@devel
  radical.pilot        : 0.50.7-v0.50.7-99-g4193371@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.50.0-v0.50.0@devel
```

**Comment by andre-merzky** [comment]
This is now fixed and released.

**Comment by andre-merzky** [comment]
Hi Srinivas - sorry, I missed the last message...

The agent complains about `RuntimeError: LRMS has no nodes left to run units` - I think your pilot is too small (4 cores?).  For some reason, `cores_per_node` seems to be set to `0` - but I am not sure if that makes a difference.

The error on the client side seems a totally unrelated issue, and seems to be related to the process termination.  Please try first to check the pilot size, and then we'll look into the termination if that persists...

**Comment by SrinivasMushnoori** [comment]
Hey, on increasing the pilot size, I find the following message in `agent_0.err` : 

```
Traceback (most recent call last):
  File "/scratch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017745.0020/pilot.0000/rp_install/bin/radical-pilot-agent", line 71, in <module>
    bootstrap_3(sys.argv[1])
  File "/scratch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017745.0020/pilot.0000/rp_install/bin/radical-pilot-agent", line 42, in bootstrap_3
    if agent_name == 'agent_0': agent = rpa.Agent_0(agent_name)
  File "/scratch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017745.0020/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 118, in __init__
    session=self._session)
  File "/scratch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017745.0020/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 229, in create
    return impl(cfg, session)
  File "/scratch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017745.0020/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/torque.py", line 19, in __init__
    LRMS.__init__(self, cfg, session)
  File "/scratch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017745.0020/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 155, in __init__
    self._log, self._prof))
  File "/scratch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017745.0020/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 174, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger, profiler)
  File "/scratch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017745.0020/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 48, in lrms_config_hook
    raise Exception("Couldn't find orte-dvm")
Exception: Couldn't find orte-dvm

```

Complete logs are [here](https://github.com/radical-cybertools/radical.pilot/files/2255864/orte_dvm.tar.gz)

**Comment by andre-merzky** [comment]
Hmm, yes, but I don't understand it: the orte installation on BW looks good, permissions are ok, etc.  Alas,  your pilot sandbox misses the bootstrap_0 stdout/err files which would log the respective module load.  Can you please check if those are available in the sandbox?

**Comment by SrinivasMushnoori** [comment]
@andre-merzky so I checked the `pilot.00000/` directory and noticed that `bootstrap_0.err` is empty. `bootstrap_0.out` however is not. Attached [here](https://github.com/radical-cybertools/radical.pilot/files/2257596/bootstrap_0.zip)

**Comment by iparask** [comment]
@SrinivasMushnoori are you still facing this issue?

**Comment by andre-merzky** [comment]
This was fixed - but is also outdated due to general ORTE problems.
