### ISSUE TITLE
RCT Class example fails on Comet. 

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1863]
```
(rct_class)scm177@mcewan:~/RADICAL-LAB/RADICAL_DEVEL_STACK/rp/examples$ python -V
Python 2.7.14
(rct_class)scm177@mcewan:~/RADICAL-LAB/RADICAL_DEVEL_STACK/rp/examples$ radical-stack

  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/rct_class

  radical.pilot        : 0.61.0-v0.61.0-38-gc8c2aec@rct-comm
  radical.saga         : 0.60.0
  radical.utils        : 0.60.1

```

Command line:
```
python 12_unit_function.py xsede.comet_ssh
```

There are no agent side logs. No pilot sandbox.

Client side error log is [here](https://github.com/radical-cybertools/radical.pilot/files/3221035/error_log_RCT_class.zip)

Client side files are [here](https://github.com/radical-cybertools/radical.pilot/files/3221038/Client_side_sandbox.zip)

**Comment by andre-merzky** [comment]
Can you please run `rm -rf $HOME/.saga $HOME/.radical/saga` and try again?  Thanks.

**Comment by SrinivasMushnoori** [comment]
To clarify, is this on the agent side or the client side?

**Comment by andre-merzky** [comment]
On Comet.

**Comment by SrinivasMushnoori** [comment]
Same thing happens.

**Comment by andre-merzky** [comment]
Would you mind adding the client side logs again, please?  Just to confirm its indeed the same error...

**Comment by SrinivasMushnoori** [comment]
Haha yes, apologies. I just updated with logs. Updated the previous comment.

**Comment by andre-merzky** [comment]
Hi Srinivas - it took me a while to understand this, but the fixes are now scheduled for merge (in radical-cybertools/radical.utils/pull/165 and radical-cybertools/radical.utils/pull/165).

**Comment by SrinivasMushnoori** [comment]
@andre-merzky I am seeing that a merge has been made. The stack I am using is:
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/rct_class

  radical.pilot        : 0.61.0-v0.61.0-38-gc8c2aec@rct-comm
  radical.saga         : 0.60.0
  radical.utils        : 0.60.1-v0.60.1-3-g0279d79@master
```
It is still failing. I want to confirm if this is the correct stack.

**Comment by andre-merzky** [comment]
The fixes still need a code review before being merged, so that stack will indeed still fail.  I hope to get that released today, but probably not before the class...

**Comment by SrinivasMushnoori** [comment]
I see. I do have something that might be of use to you to diagnose. 
I realize that I need to use the appropriate `saga` branch too: and I did just that. New stack is:

```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/rct_class

  radical.pilot        : 0.61.0-v0.61.0-38-gc8c2aec@rct-comm
  radical.saga         : 0.60.0-v0.60.0-2-gcbfe6df@hotfix-delay_expand
  radical.utils        : 0.60.1-v0.60.1-3-g0279d79@master
```

This DOES create unit sandboxes, but all tasks still fail. Fetching logfiles and going a `grep ERROR *log` returns:

```
pmgr.0000.launching.0.child.log:2019-05-28 11:53:41,195: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
pmgr.0000.log:2019-05-28 11:53:41,244: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : [Callback]: pilot 'pilot.0000' failed (exit on error)
pmgr.0000.log:2019-05-28 11:53:41,244: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : abort: RuntimeError('pilot pilot.0000 failed - fatal!',)
```

Uploading all log files shortly.

**Comment by andre-merzky** [comment]
Be patient - that stack will indeed not work.  There are fixes needed in other layers, too.

**Comment by andre-merzky** [comment]
FWIW, your run failed for different reasons:

```
sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
```

You may want to submit to the `compute` queue, for example, where that time limit would be valid.

**Comment by andre-merzky** [comment]
FWIW, your run failed for different reasons:

```
sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
```

You may want to submit to the `compute` queue, for example, where that time limit would be valid.

**Comment by andre-merzky** [comment]
This stack should work now:
```
$ rs

  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/merzky/radical/radical.pilot/ve

  radical.pilot        : 0.61.0-v0.61.0-42-g5001fad8@rct-comm
  radical.saga         : 0.60.0-v0.60.0-2-gcbfe6dfb@hotfix-delay_expand
  radical.utils        : 0.60.2
```

**Comment by SrinivasMushnoori** [comment]
Thanks Andre. Apologies, didn't mean to be impatient. Just thought you might be able to use the information. Will be testing in a bit.

**Comment by andre-merzky** [comment]
No worries, Srinivas - let me know how it goes! :-)

**Comment by SrinivasMushnoori** [comment]
Oddly enough, still fails. 
[Logs here](https://github.com/radical-cybertools/radical.pilot/files/3229226/still_fails.tar.gz)

`radical-stack`
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/rct_class

  radical.pilot        : 0.61.0-v0.61.0-38-gc8c2aec@rct-comm
  radical.saga         : 0.60.0-v0.60.0-2-gcbfe6df@hotfix-delay_expand
  radical.utils        : 0.60.2-v0.60.2-1-g1537e00@master
```

**Comment by andre-merzky** [comment]
indeed - but you should see a pilot sandbox now, can you attach it?  What is the resource label you are using?

**Comment by SrinivasMushnoori** [comment]
Sandbox is [here](https://github.com/radical-cybertools/radical.pilot/files/3229371/sandbox.tar.gz)
I do see a pilot sandbox. Unit sandboxes too. But they are empty. 
Resource label is `xsede.comet_ssh` as mentioned in original post on this ticket:
```
python 12_unit_function.py xsede.comet_ssh
```

**Comment by andre-merzky** [comment]
I will look into the the sandbox - but you will need to use `xsede.comet_ssh_funcs` to trigger the func_execution configuration...

**Comment by SrinivasMushnoori** [comment]
I see. Let me give that a shot.

**Comment by andre-merzky** [comment]
You may want to remove `/home/mushnoor/radical.pilot.sandbox/ve.xsede.comet_ssh.0.61.0` on comet, it is incomplete.  It will not affect the `xsede.comet_ssh_funcs` run though, FWIW (that will create a new ve)

**Comment by SrinivasMushnoori** [comment]
I am unable to use the config file. I find the following in the config file:
```
    "xsede.comet_ssh_funcs"  : {
        "project"  : "TG-MCB090174",
        "queue"    : "compute",
        "schema"   : "gsissh",
        "cores"    : 64
    },
```

But running `python 12_unit_function.py xsede.comet_ssh_funcs` gives me the following error:

```
        caught Exception: Resource 'xsede.comet_ssh_funcs' is not known.
```

**Comment by andre-merzky** [comment]
Did you update the radical-pilot branch?  What is your radical-stack now?

**Comment by SrinivasMushnoori** [comment]
Yes I did, my stack is
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/rct_class

  radical.pilot        : 0.61.0-v0.61.0-42-g5001fad@rct-comm
  radical.saga         : 0.60.0-v0.60.0-2-gcbfe6df@hotfix-delay_expand
  radical.utils        : 0.60.2-v0.60.2-1-g1537e00@master
```

**Comment by SrinivasMushnoori** [comment]
I am trying a fresh RP install. Upon further inspection this is beginning to look like some sort of branch/version conflict.

**Comment by andre-merzky** [comment]
Hmm, I am confident that the label is defined in that stack:
```
$ grep -r comet_ssh_funcs src/
src/radical/pilot/configs/resource_xsede.json:    "comet_ssh_funcs": {
```

```
$ rs

  python               : 2.7.15rc1
  pythonpath           :
  virtualenv           : /home/merzky/radical/radical.pilot.devel/ve

  radical.pilot        : 0.61.0-v0.61.0-42-g5001fad8@rct-comm
  radical.saga         : 0.60.0-v0.60.0-1-g2d2601ee@hotfix-delay_expand
  radical.utils        : 0.60.1-v0.60.1-2-g1ddce48@fix-delay_expand
```

One strange thing: your RP commit tag is `g5001fad`, mine is `g5001fad8`.  But it seems like the correct one anyway.  I am not sure whats up.  Can you check if the right config file was installed?

**Comment by SrinivasMushnoori** [comment]
Fresh install works! 
I'm setting up experiments now. They'll be done soon. Closing for now.

**Comment by andre-merzky** [comment]
great :-)
