### ISSUE TITLE
radical-pilot-bridges not found on Bridges2

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#2347]
I'm trying to migrate `radical.repex` on Bridges 2 and I am consistently getting the following error when RP tries to launch the agent:
```
bootstrap agent agent.0
failed agent.0
--------------
RADICAL Utils -- Stacktrace [247887] [MainThread]
paraskev  247887  246462 14 12:02 ?        00:00:00          \_ rp.agent.0
Traceback (most recent call last):
File "/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/bin/radical-pilot-agent", line 51, in bootstrap_3
if aid == 'agent.0': agent = rp.Agent_0(cfg, session)
File "/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/agent_0.py", line 76, in __init__
self._cmgr.start_bridges()
File "/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/utils/component.py", line 171, in start_bridges
out, err, ret = ru.sh_callout('radical-pilot-bridge %s' % fname)
File "/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/lib/python3.8/site-packages/radical/utils/shell.py", line 30, in sh_callout
p = sp.Popen(cmd, stdout=stdout, stderr=stderr, shell=shell)
File "/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/lib/python3.8/subprocess.py", line 858, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/lib/python3.8/subprocess.py", line 1706, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'radical-pilot-bridge'
--------------
finalize agent.0
```
The branch is fully synced with `devel` and my overall stack is:
```
 python               : /home/iparask/miniconda3/envs/repex_test/bin/python3
  pythonpath           :
  version              : 3.9.2
  virtualenv           : repex_test
  radical.entk         : 1.6.0-v1.5.12-71-gc1cc422@devel
  radical.gtod         : 1.5.0
  radical.pilot        : 1.6.0-v1.6.0-188-g345a6aa@user-repex
  radical.repex        : 0.72.0-f395f96@feature-multi_md_steps
  radical.saga         : 1.6.1
  radical.utils        : 1.6.0
```

In addition, the boostrapper adds in `PYTHONPATH` the path of `rp_install` folder:
```
VIRTENV           : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0
VIRTENV normalized: /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0
PYTHON            : /opt/packages/anaconda3/2020.11/bin/python
PYTHON_VERSION    : 3.8
PIP               : /opt/packages/anaconda3/2020.11/bin/python -m pip
PIP version       : pip 20.2.4 from /opt/packages/anaconda3/2020.11/lib/python3.8/site-packages/pip (python 3.8)
1615824110.0000,ve_setup_start,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
virtenv_create    : TRUE
virtenv_update    : FALSE
rp install sources:  radical.utils-1.6.0/ radical.saga-1.6.1/ radical.pilot-1.6.0-v1.6.0-188-g345a6aa-user-repex/
rp install target : SANDBOX
rp install lock   : FALSE
virtenv /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0 exists
1615824110.0000,ve_activate_start,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
VIRTENV activated : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0
RP_PATH           : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/bin
PYTHON            : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/bin/python
PYTHON_VERSION    : 3.8
PIP               : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/bin/python -m pip
PIP version       : pip 21.0.1 from /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/lib/python3.8/site-packages/pip (python 3.8)
VE_MOD_PREFIX init: /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/lib/python3.8/site-packages
VE_MOD_PREFIX     : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/lib/python3.8/site-packages
RP_MOD_PREFIX     : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/rp_install/lib/python3.8/site-packages
VE_PYTHONPATH     :
1615824114.0000,ve_activate_stop,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
do not update virtenv /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0
1615824114.0000,rp_install_start,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
Using RADICAL-Pilot install sources ' radical.utils-1.6.0/ radical.saga-1.6.1/ radical.pilot-1.6.0-v1.6.0-188-g345a6aa-user-repex/'
VE_MOD_PREFIX     : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/lib/python3.8/site-packages
VIRTENV           : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0
SANDBOX           : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000
VE_LOC_PREFIX     :
using local install tree
PYTHONPATH        : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/lib/python3.8/site-packages::
RP_LOC_PREFIX     : /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/lib/python3.8/site-packages
RADICAL_MOD_PREFIX: /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/lib/python3.8/site-packages/radical/
```

Last, `radical-pilot-bridge` is installed under `rp_install/bin`:
```
[paraskev@bridges2-login011 bin]$ pwd
/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/bin
[paraskev@bridges2-login011 bin]$ ls
__pycache__                    radical-pilot-bridge         radical-pilot-create-static-ve  radical-pilot-fetch-profiles  radical-pilot-stats.plot  radical-utils-env.sh          radical-utils-version
radical-bridge                 radical-pilot-bson2json      radical-pilot-deploy-ompi.sh    radical-pilot-inspect         radical-pilot-version     radical-utils-fix-headers.pl  ru-runcheck.sh
radical-pilot-agent            radical-pilot-cleanup        radical-pilot-fetch-db          radical-pilot-prte2prof       radical-pilot-worker      radical-utils-mongodb.py      ru.json.sh
radical-pilot-agent-funcs      radical-pilot-close-session  radical-pilot-fetch-json        radical-pilot-run-session     radical-saga-version      radical-utils-pwatch
radical-pilot-agent-statepush  radical-pilot-component      radical-pilot-fetch-logfiles    radical-pilot-stats           radical-stack             radical-utils-pylint.sh
[paraskev@bridges2-login011 bin]$
```

**Comment by mtitov** [comment]
@iparask are there errors in `bootstrap_0.out` during `radical.pilot` pip installation?

**Comment by iparask** [comment]
They are in `agent.0.out`.

**Comment by andre-merzky** [comment]
Can you please attach `bootstrap_0.out` and `bootstrap_2.sh`?  Is `rp_install/bin/radical-pilot-bridge` executable?  Can you run it from command line when the VE is activated?

**Comment by iparask** [comment]
I renamed `bootstrap_2.sh` to `bootstrap_2.log`. There you go:

[bootstrap_0.log](https://github.com/radical-cybertools/radical.pilot/files/6151523/bootstrap_0.log)
[bootstrap_2.log](https://github.com/radical-cybertools/radical.pilot/files/6151543/bootstrap_2.log)

> Is rp_install/bin/radical-pilot-bridge executable?
Yes, it is.

>Can you run it from command line when the VE is activated?

I am not sure what I did replicates RP correctly, but I hope so:
```
[paraskev@r001 radical.pilot.sandbox]$ module reset
The system default contains no modules
  (env var: LMOD_SYSTEM_DEFAULT_MODULES is empty)
  No changes in loaded modules

[paraskev@r001 radical.pilot.sandbox]$ module load gcc
[paraskev@r001 radical.pilot.sandbox]$ module load openmpi/3.1.6-gcc8.3.1
[paraskev@r001 radical.pilot.sandbox]$ module load anaconda3
[paraskev@r001 radical.pilot.sandbox]$ source activate ve.xsede.bridges2.1.6.0
[paraskev@r001 radical.pilot.sandbox]$ source activate ve.xsede.bridges2.1.6.0/
(/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0) [paraskev@r001 pilot.0000]$ export PYTHONPATH=$PWD/rp_install/lib/python3.8/site-packages/:/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/lib/python3.8/site-packages/
(/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0) [paraskev@r001 pilot.0000]$ export PATH=$PWD/rp_install/bin/:/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0/bin/:$PATH
(/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0) [paraskev@r001 pilot.0000]$ radical-
radical-bridge                  radical-pilot-cleanup           radical-pilot-fetch-json        radical-pilot-stats             radical-utils-env.sh
radical-pilot-agent             radical-pilot-close-session     radical-pilot-fetch-logfiles    radical-pilot-stats.plot        radical-utils-fix-headers.pl
radical-pilot-agent-funcs       radical-pilot-component         radical-pilot-fetch-profiles    radical-pilot-version           radical-utils-mongodb.py
radical-pilot-agent-statepush   radical-pilot-create-static-ve  radical-pilot-inspect           radical-pilot-worker            radical-utils-pwatch
radical-pilot-bridge            radical-pilot-deploy-ompi.sh    radical-pilot-prte2prof         radical-saga-version            radical-utils-pylint.sh
radical-pilot-bson2json         radical-pilot-fetch-db          radical-pilot-run-session       radical-stack                   radical-utils-version
(/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.0) [paraskev@r001 pilot.0000]$ radical-pilot-bridge
bash: /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/bin/radical-pilot-bridge: python: bad interpreter: No such file or directory
```

**Comment by andre-merzky** [comment]
> bash: /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/bin/radical-pilot-bridge: python: bad interpreter: No such file or directory

That actually was just fixed in devel (see #2346) - would you mind merging from devel and to rerun?

**Comment by iparask** [comment]
I'm still getting the same error.

**Comment by andre-merzky** [comment]
Wait, you get the same error like
```sh
bash: /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018701.0003/pilot.0000/rp_install/bin/radical-pilot-bridge: \
python: bad interpreter: No such file or directory
```
?  Then you are not on devel, that should be `python3` now.  But you likely mean the error during runtime:
```sh
FileNotFoundError: [Errno 2] No such file or directory: 'radical-pilot-bridge'
```
?  I cannot wrap my head around this really: if `rp_install` looks good and `PATH` is set, why would it not run?  Did that work at some point in the past?  I seem to remember that you used Bridges2 before?

**Comment by iparask** [comment]
I still see the original error. I am using `user/repex` which is in sync with devel. One thing I can say is that in the `rp_install` bin folder, the executables do not have `/usr/bin/python3` but `python`. However, I do not think this is the issue because it cannot be found.

Do you want access to the sandbox folder?

**Comment by iparask** [comment]
If you remember from our discussion yesterday there is an error from pip saying that it cannot build the `wheel` because the version string is not based on `PEP 440`. For example:
```
# -------------------------------------------------------------------
#
# update radical.pilot-1.6.1-v1.6.1-26-gf81427f-devel/ via pip
# cmd: /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.1/bin/python -m pip install  --src '/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/rp
.session.js-17-185.jetstream-cloud.org.iparask.018703.0004/pilot.0000/rp_install/src' --prefix '/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/rp.session.js-17-185.jetstrea
m-cloud.org.iparask.018703.0004/pilot.0000/rp_install' --no-deps --no-cache-dir --no-build-isolation radical.pilot-1.6.1-v1.6.1-26-gf81427f-devel/
#
Processing ./radical.pilot-1.6.1-v1.6.1-26-gf81427f-devel
Building wheels for collected packages: radical.pilot
  Building wheel for radical.pilot (setup.py): started
  Building wheel for radical.pilot (setup.py): finished with status 'done'
  Created wheel for radical.pilot: filename=radical.pilot-1.6.1_v1.6.1_26_gf81427f_devel-py3-none-any.whl size=1233133 sha256=d013f7af45742060c285c9f86f94109a5e111f1c0bd6393070bfc93a5
638f74b
  Stored in directory: /tmp/pip-ephem-wheel-cache-7eit9iea/wheels/fb/d0/68/d00d5184d638b15c192f4ac9ec091022dd1311604cad9e4b6b
  WARNING: Built wheel for radical.pilot is invalid: Metadata 1.2 mandates PEP 440 version, but '1.6.1-v1.6.1-26-gf81427f-devel' is not
Failed to build radical.pilot
Installing collected packages: radical.pilot
    Running setup.py install for radical.pilot: started
    Running setup.py install for radical.pilot: finished with status 'done'
  DEPRECATION: radical.pilot was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issu
e reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed radical.pilot-1.6.1-v1.6.1-26-gf81427f-devel
#
# SUCCESS
#
```

In my latest run, I forced the version to be equal to the base version for the devel branch. As a result, `pip` installs `radical.pilot-1.6.1`:
```
# -------------------------------------------------------------------
#
# update radical.pilot-1.6.1/ via pip
# cmd: /ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/ve.xsede.bridges2.1.6.1/bin/python -m pip install  --src '/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/rp
.session.js-17-185.jetstream-cloud.org.iparask.018703.0007/pilot.0000/rp_install/src' --prefix '/ocean/projects/mcb110096p/paraskev/radical.pilot.sandbox/rp.session.js-17-185.jetstrea
m-cloud.org.iparask.018703.0007/pilot.0000/rp_install' --no-deps --no-cache-dir --no-build-isolation radical.pilot-1.6.1/
#
Processing ./radical.pilot-1.6.1
Building wheels for collected packages: radical.pilot
  Building wheel for radical.pilot (setup.py): started
  Building wheel for radical.pilot (setup.py): finished with status 'done'
  Created wheel for radical.pilot: filename=radical.pilot-1.6.1-py3-none-any.whl size=1185992 sha256=265df2caf840fa7e864052205a7634ad00e14efb2fdcca0f69a335258f3f19bb
  Stored in directory: /tmp/pip-ephem-wheel-cache-0ixcxmvn/wheels/98/c0/ac/2e7e1baf7d57047e77229f3533690f4c957f8847d0229bb153
Successfully built radical.pilot
Installing collected packages: radical.pilot
Successfully installed radical.pilot-1.6.1
#
# SUCCESS
#
# -------------------------------------------------------------------
```
This executed correctly. Also, on Bridges2 the VE pip version is `pip 21.0.1` and the python version is `Anaconda 3.8`.

**Comment by andre-merzky** [comment]
I can't really convey how angry I am about this.  Who can be so stupid and think that breaking other peoples versioning scheme is a good thing to release into the wield?  Fuck Python deployment, really, once more...

Thanks @iparask for tracking this down, I'll take care of it.

**Comment by andre-merzky** [comment]
for reference: https://www.python.org/dev/peps/pep-0440/#dvcs-based-version-labels

**Comment by andre-merzky** [comment]
@iparask : could you please give the RP branch `hotfix/sdist_version` a try?  Thank you!

**Comment by iparask** [comment]
Installation in my VE, not Bridges2, fails with the following error:
```
Processing /home/iparask/Git/RADICAL/radical.pilot
Requirement already satisfied: radical.utils>=1.5.2 in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.pilot==1.6.1) (1.6.0)
Requirement already satisfied: radical.saga>=1.5.2 in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.pilot==1.6.1) (1.6.1)
Requirement already satisfied: pymongo in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.pilot==1.6.1) (3.11.0)
Requirement already satisfied: python-hostlist in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.pilot==1.6.1) (1.21)
Requirement already satisfied: netifaces in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.pilot==1.6.1) (0.10.9)
Requirement already satisfied: setproctitle in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.pilot==1.6.1) (1.2.2)
Requirement already satisfied: ntplib in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.pilot==1.6.1) (0.3.4)
Requirement already satisfied: parse in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.saga>=1.5.2->radical.pilot==1.6.1) (1.19.0)
Requirement already satisfied: apache-libcloud in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.saga>=1.5.2->radical.pilot==1.6.1) (3.3.1)
Requirement already satisfied: wheel in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.utils>=1.5.2->radical.pilot==1.6.1) (0.36.2)
Requirement already satisfied: pyzmq in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.utils>=1.5.2->radical.pilot==1.6.1) (22.0.3)
Requirement already satisfied: regex in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.utils>=1.5.2->radical.pilot==1.6.1) (2020.11.13)
Requirement already satisfied: msgpack in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.utils>=1.5.2->radical.pilot==1.6.1) (1.0.2)
Requirement already satisfied: radical.gtod in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.utils>=1.5.2->radical.pilot==1.6.1) (1.5.0)
Requirement already satisfied: future in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.utils>=1.5.2->radical.pilot==1.6.1) (0.18.2)
Requirement already satisfied: colorama in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from radical.utils>=1.5.2->radical.pilot==1.6.1) (0.4.4)
Requirement already satisfied: requests>=2.5.0 in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from apache-libcloud->radical.saga>=1.5.2->radical.pilot==1.6.1) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from requests>=2.5.0->apache-libcloud->radical.saga>=1.5.2->radical.pilot==1.6.1) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from requests>=2.5.0->apache-libcloud->radical.saga>=1.5.2->radical.pilot==1.6.1) (1.26.3)
Requirement already satisfied: idna<3,>=2.5 in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from requests>=2.5.0->apache-libcloud->radical.saga>=1.5.2->radical.pilot==1.6.1) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages (from requests>=2.5.0->apache-libcloud->radical.saga>=1.5.2->radical.pilot==1.6.1) (4.0.0)
Building wheels for collected packages: radical.pilot
  Building wheel for radical.pilot (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/iparask/miniconda3/envs/rct_devel/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-hrra1e40/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-hrra1e40/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-g1phwzz1
       cwd: /tmp/pip-req-build-hrra1e40/
  Complete output (323 lines):
  /home/iparask/miniconda3/envs/rct_devel/lib/python3.9/site-packages/setuptools/dist.py:472: UserWarning: The version specified ('1.6.1-v1.6.1-27-g240eedb@hotfix-sdist_version') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    warnings.warn(
  running sdist
  running egg_info
```

I'm sorry

**Comment by andre-merzky** [comment]
How did you run the install?  `pip install .`?

**Comment by iparask** [comment]
Yes, `pip install . --upgrade`

**Comment by iparask** [comment]
Hello @andre-merzky, this seems to do the trick:
```
(rct_devel) iparask@js-17-185:~/Git/RADICAL/radical.pilot$ git diff setup.py
diff --git a/setup.py b/setup.py
index 7c90d40..871d3b4 100755
--- a/setup.py
+++ b/setup.py
@@ -106,7 +106,7 @@ def get_version(_mod_root):
         # make sure the version files exist for the runtime version inspection
         _path = '%s/%s' % (src_root, _mod_root)
         with open(_path + '/VERSION', 'w') as f:
-            f.write(_version + '\n')
+            f.write(_version_base + '\n')

         _sdist_name = '%s-%s.tar.gz' % (name, _version_base)
       # _sdist_name = _sdist_name.replace('/', '-')
```

pip executes first `python setup.py sdist` which tries to create a `tar.gz` with version `1.6.1-v1.6.1-27-g240eedb@hotfix-sdist_version`. After that it tries to find  `dist/radical.pilot-1.6.1.tar.gz` which does not exist.

**Comment by andre-merzky** [comment]
Yes - but then `radical_stack` will not be able to obtain the full version info anymore.  We probably have to store both now...  I am not sure I understand how the full version creeps into the tar name - that is explicitly set to `_version_base` in the lines you show above...

**Comment by eirrgang** [comment]
Can you use the [build](https://pypa-build.readthedocs.io/en/latest/api.html) package? That should automatically generate normative package names and provide some future-proofing. Note `build.ProjectBuilder.build('sdist')` returns the full path to the built sdist.
