### ISSUE TITLE
NB documentation build process on readthedocs

### ISSUE THREAD

**Issue by kartikmodi** [radical-cybertools/radical.pilot#2553]
Build and run the NB documentation on readthedocs container.

**Comment by mturilli** [comment]
@kartikmodi should we convert this to a discussion?

**Comment by kartikmodi** [comment]
> 

Yes, it should have been a discussion. Didn't think of it. 
I created this, particularly for fixing errors on readthedocs,  to push changes to a new branch, so needed an issue number. 

I am creating a new discussion for points 2 and point 3, removing from here. 
Point 1 should stay here.

**Comment by mturilli** [comment]
No need to open a new discussion, just let's convert this ticket to a discussion. I am going to do it now.

**Comment by mtitov** [comment]
Couple quick comments

- need to check that wherever `copyright` is used (in files that were edited) it follows the following values (see internal document in google-drive: `/Documents/RADICAL Names`) - related to `docs/source/conf.py`
```
Header information in modules of code

__author__	= 'RADICAL-Cybertools Team'
__email__	= 'info@radical-cybertools.org'
__copyright__	= 'Copyright 20XX, The RADICAL-Cybertools Team'
__license__	= 'MIT'

Footer for web pages

Copyright 20XX, The RADICAL-Cybertools Team (info@radical-cybertools.org)

```

- Numeration can be fixed at this point (e.g., `y. Configuration` -> set an order number instead of `y` ; same for `x. Quickstart`)

**Comment by kartikmodi** [comment]
> Couple quick comments
> 
> * need to check that wherever `copyright` is used (in files that were edited) it follows the following values (see internal document in google-drive: `/Documents/RADICAL Names`) - related to `docs/source/conf.py`
> 
> ```
> Header information in modules of code
> 
> __author__	= 'RADICAL-Cybertools Team'
> __email__	= 'info@radical-cybertools.org'
> __copyright__	= 'Copyright 20XX, The RADICAL-Cybertools Team'
> __license__	= 'MIT'
> 
> Footer for web pages
> 
> Copyright 20XX, The RADICAL-Cybertools Team (info@radical-cybertools.org)
> ```
> 
> * Numeration can be fixed at this point (e.g., `y. Configuration` -> set an order number instead of `y` ; same for `x. Quickstart`)

Thanks a lot @mtitov . 
1. I have fixed the copyright with updated RADICAL-Names and used `2022` as copyright year, if that's ok. 
This is now in sync with devel. 


2. For Numerations, the configuration and quickstart notebooks are not included in the build. They are present in src but is not used anywhere as it's included in index.rst. I have not deleted them.  All the sources are presented in `docs/source/3`.
Numerations are handled by sphinx automatically at build time and I have recently removed any manual numbering that I was doing earlier. 
you can see the numerations output at  https://radicalpilot-nb-docs.readthedocs.io/en/latest/

**Comment by andre-merzky** [comment]
> @andre-merzky @mtitov @mturilli I have detailed all the build process on RTD at https://github.com/radical-cybertools/radical.pilot/tree/docs/nb_section3/docs/source#details-on-readthedocs-for-documentation-build-with-notebooks

Thank you!  Can you please list in the document what settings you changed in the RTD admin space, and what env variables you configured?

> The only reason this ticket is open because of build time. See - https://readthedocs.org/projects/radicalpilot-nb-docs/builds/16960181/ The current time is 29.6 mins. If I add any more notebooks, the build is timedout.
> 
> If you think I should create a new issue for this, we can actually close this one.

That sounds reasonable.

**Comment by kartikmodi** [comment]
> > @andre-merzky @mtitov @mturilli I have detailed all the build process on RTD at https://github.com/radical-cybertools/radical.pilot/tree/docs/nb_section3/docs/source#details-on-readthedocs-for-documentation-build-with-notebooks
> 
> Thank you! Can you please list in the document what settings you changed in the RTD admin space, and what env variables you configured?
> 
> > The only reason this ticket is open because of build time. See - https://readthedocs.org/projects/radicalpilot-nb-docs/builds/16960181/ The current time is 29.6 mins. If I add any more notebooks, the build is timedout.
> > If you think I should create a new issue for this, we can actually close this one.
> 
> That sounds reasonable.

Added now. Have a read and let me if anything seems missing. 
Opening a new ticket for build time problem.

**Comment by kartikmodi** [comment]
Closing this, since documented

**Comment by andre-merzky** [comment]
@kartikmodi: This ticket was closed, but a branch `feature/issue_2553` still exists.  What is planned for that branch (last commit 5 months ago)?

**Comment by kartikmodi** [comment]
oops. This branch should not exist. I committed in another branch dosc/nb_section3 which is on review. @andre-merzky 
deleting this one.
