### ISSUE TITLE
srun + mpi4py on Frontera broken

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2584]
```
$ /bin/srun -N 1 --ntasks 2 --cpus-per-task 1 --nodelist=c204-015,c204-015 hostname
srun: error: Required nodelist includes more nodes than permitted by max-node count (2 > 1). Eliminating nodes from the nodelist.
c204-015.frontera.tacc.utexas.edu
c204-015.frontera.tacc.utexas.edu

$ /bin/srun -N 2 --ntasks 2 --cpus-per-task 1 --nodelist=c204-015,c204-015 hostname
# hangs

$  /bin/srun --nodes 1 --ntasks 2 --cpus-per-task 1 --nodelist=c204-015 hostname
c204-015.frontera.tacc.utexas.edu
c204-015.frontera.tacc.utexas.edu
```

**Comment by andre-merzky** [comment]
I think I fixed this now - but srun still does not play nice with MPI4PI.  I had to open a frontera support ticket for that and a resolution of this issue will have to wait until that gets resolved.

**Comment by mtitov** [comment]
This should be fixed by eliminating node names duplications in `--nodelist` option - fixed in e5329c2

**Comment by andre-merzky** [comment]
@andre-merzky : check on Frontera

**Comment by andre-merzky** [comment]
@AymenFJA : please test the current state of affairs - thanks

**Comment by AymenFJA** [comment]
UPDATE: I tested the example above and I confirm that it still hangs:

```
 /bin/srun -N 2 --ntasks 2 --cpus-per-task 1 --nodelist=c206-013,c206-013 hostname
hangs
```

With RP (interactively) we see this error:
```
login2.frontera(1016)$ cat master.000000.err
srun: cluster configuration lacks support for cpu binding
srun: cluster configuration lacks support for cpu binding
```

**Comment by andre-merzky** [comment]
The hanging `srun` command should result in a TACC-ticket IMHO - @AymenFJA , would you open one, please?

**Comment by mtitov** [comment]
@AymenFJA may I ask you to run several tests more with the following options
(* btw, there should be no duplication of host names in `--nodelist`, that your command is not based on the latest release, right?)
- `--exclusive`
- `--threads-per-core 1`
- running that command please be sure that env variable `OMP_NUM_THREADS` is set as well, along with `--cpus-per-task`
- after the previous to try without `OMP_NUM_THREADS` and `--cpus-per-task`
- check the list with `srun --mpi=list` and try `srun` command with `--mpi=pmi2` (and maybe check other values from the output of `srun --mpi=list`)

**Comment by mtitov** [comment]
> `$ /bin/srun -N 2 --ntasks 2 --cpus-per-task 1 --nodelist=c204-015,c204-015 hostname`
> `# hangs`

@andre-merzky it is incorrect command, isn't it? asked 2 nodes with `-N 2`, but `--nodelist` has the same name for nodes, so it is 1 node (?)

**Comment by andre-merzky** [comment]
I am not sure how slurm resolves this, but I would at least expect an error message and not the request to hang.

**Comment by mtitov** [comment]
> I am not sure how slurm resolves this, but I would at least expect an error message and not the request to hang.

that command is not the case for RP, since RP will not generate it this way (`--nodes` will always correspond to `--nodelist` option). But if to speak generally, then agree, looks like the way Slurm is configured it doesn't handle it correctly

**Comment by AymenFJA** [comment]
The output of `srun --mpi=list`: returns: 
```
c202-005[clx](1010)$ srun --mpi=list
srun: MPI types are...
srun: cray_shasta
srun: none
srun: pmi2
srun: pmix
srun: pmix_v3
```
I did export `OMP_NUM_THREADS`

Trying the commands suggested by Mikhail seems to return the same thing:

1- If I do the regular command: `/bin/srun --mpi=pmix -N 1 --ntasks 2 --cpus-per-task 1 --nodelist=c202-005 hostname` it hangs for ever.
2- if I do `/bin/srun --exclusive --threads-per-core 1 -N 1 --ntasks 2 --cpus-per-task 1 --nodelist=c202-005 hostname` I get:
```
srun: cluster configuration lacks support for cpu binding
```

**Comment by eirrgang** [comment]
Did you try `--mpi=pmi2`?

Is the partition you are using _expected_ to support cpu binding, or is this maybe a partition that is configured as `Shared` (overriding `exclusive`)?

**Comment by mtitov** [comment]
> I would suggest to close that issue since we switched to Flux for Frontera

agree, and couple things to keep in mind (possible solutions we have, but haven't tested them on Frontera)
- we've updated env setup procedure for LM - now we use `bs0_orig` as base - "clean" env which is not touched by RP
- use parameter `"system_architecture": {"exclusive": true}` in the resource configuration (will set `--exclusive` for SBATCH and use `--exact` in SRUN)
- in one of the projects we had issue with importing `mpi4py` which was caused by different envs overlapping - solution was to put `module reset` and then load target env with `mpi4py` (all that as part of task's `pre_exec`)

**Comment by andre-merzky** [comment]
Oops - I mixed up frontier and frontera....  But either way, I'll close this until we have new data / projects on Frontera....
